### ISSUE TITLE
No arm64 natives for macOS

### ISSUE THREAD

**Issue by cliserkad** [OpenCraft-Studios/OpenCraft#26]
**Describe the bug**
There are no arm64 natives for macOS in jar

**To Reproduce**
1. Download opencraft.jar from release
2. Run `java -jar opencraft.jar`
3. See error

**Expected behavior**
Natives should load and game should start, showing main menu.

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.6.1
 - Version: 25e0eed

**Additional context**
Stack Trace:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: /Users/cliserkad/Downloads/natives/liblwjgl.dylib: dlopen(/Users/cliserkad/Downloads/natives/liblwjgl.dylib, 0x0001): tried: '/Users/cliserkad/Downloads/natives/liblwjgl.dylib' (fat file, but missing compatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/cliserkad/Downloads/natives/liblwjgl.dylib' (no such file), '/Users/cliserkad/Downloads/natives/liblwjgl.dylib' (fat file, but missing compatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2399)
	at java.base/java.lang.Runtime.load0(Runtime.java:852)
	at java.base/java.lang.System.load(System.java:2030)
	at org.lwjgl.Sys$1.run(Sys.java:70)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
	at org.lwjgl.Sys.loadLibrary(Sys.java:96)
	at org.lwjgl.Sys.<clinit>(Sys.java:117)
	at net.opencraft.OpenCraft.getSystemTime(OpenCraft.java:134)
	at net.opencraft.Timer.<init>(Timer.java:23)
	at net.opencraft.OpenCraft.<init>(OpenCraft.java:100)
	at net.opencraft.client.Main.main(Main.java:82)
```

**Comment by cliserkad** [comment]
Fixed!!
